### ISSUE TITLE
Request Update ko.json 1.28.0

### ISSUE THREAD

**Issue by gung4561** [ccfolia/ccfolia-i18n#19]
[ko.json](https://github.com/ccfolia/ccfolia-i18n/files/13373147/ko.json)

Githubの使い方が下手なのでこちらに送ります。 韓国語UI翻訳ファイルです。 どうか反映をお願いします。

**Comment by ysakasin** [comment]
@gung4561 
翻訳の寄稿ありがとうございます。
#20 にて取り込みましたので、次回リリースの際に反映します。
