### ISSUE TITLE
Request Update ko.json 1.29.0

### ISSUE THREAD

**Issue by gung4561** [ccfolia/ccfolia-i18n#21]
[ko.json](https://github.com/user-attachments/files/15964973/ko.json)

以前、韓国語UI翻訳の寄稿をさせていただいたCCFOLIAのユーザーです。
Githubの使い方が下手なのでこちらに送ります。
韓国語UI翻訳ファイルです。
反映をお願いします。

ありがとうございます。

**Comment by ysakasin** [comment]
ありがとうございます。いただいたファイルの内容を確認します。
