### ISSUE TITLE
韓国語UI翻訳 .1.30

### ISSUE THREAD

**Issue by gung4561** [ccfolia/ccfolia-i18n#23]
[ko.1.30.json](https://github.com/user-attachments/files/16705897/ko.1.30.json)

以前、韓国語UI翻訳の寄稿をさせていただいたCCFOLIAのユーザーです。
Githubの使い方が下手なのでこちらに送ります。
韓国語UI翻訳ファイルです。
反映をお願いします。

ありがとうございます。

**Comment by ysakasin** [comment]
@gung4561 寄稿ありがとうございました。次回リリースにて反映いたします。
